name: RSS Kamerstukken VWS
on:
  schedule:
    # Runs every 4 hours
    - cron: '*/5 * * * *'

jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2

    # Set-up R
    - name: Install dependencies
      run: install.packages("tidyRSS")
      shell: Rscript {0}
    # Run R script
    - name: RSS VWS
      run: Rscript rss_vws.R

 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name "Marino van Zelst"
        git config --local user.email "j.m.vanzelst@tilburguniversity.edu"
        git add .
        git commit -m "Add changes"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
